CREATE TABLE authorities(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    authority VARCHAR(30) NOT NULL UNIQUE,
    CONSTRAINT chk_authority CHECK (authority IN ('ROLE_UNCONFIRMED_USER', 'ROLE_USER', 'ROLE_ADMIN'))
);